# OnePassword Operator items
# - Each OnePasswordItem creates or updates a Kubernetes Secret with the same name.
# - Namespace is `ecom` for all resources in this repo.

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: app-configs
  namespace: ecom
spec:
  itemPath: "vaults/Ecom/items/app-configs"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: telephony-configs
  namespace: ecom
spec:
  itemPath: "vaults/Ecom/items/telephony-configs"